DROP DATABASE IF EXISTS `rent_a_car_service`;
CREATE DATABASE `rent_a_car_service`;

USE `rent_a_car_service`;

CREATE TABLE `clients`(
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`age` INT NOT NULL,
	`cnic` VARCHAR(255) NOT NULL,
	`phone_number` VARCHAR(255) NOT NULL, 
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE `cars`(
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`company_name` VARCHAR(255) NOT NULL,
	`model_number` VARCHAR(255) NOT NULL,
	`reg_number` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE `drivers`(
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`age` VARCHAR(255) NOT NULL,
	`cnic_no` VARCHAR(255) NOT NULl,
	`license_no` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `bookings`(
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`car_id` INT NOT NULL,
	`client_id` INT NOT NULL,
	`booking_date` DATE NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (car_id) REFERENCES cars(id),
	FOREIGN KEY (client_id) REFERENCES clients(id)
);