DROP DATABASE IF EXISTS `rent_a_car_service`;
CREATE DATABASE `rent_a_car_service`;

USE `rent_a_car_service`;

CREATE TABLE `clients`(
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`age` INT NOT NULL,
	`cnic` VARCHAR(255) NOT NULL,
	`phone_number` VARCHAR(255) NOT NULL, 
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE `cars`(
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`company_name` VARCHAR(255) NOT NULL,
	`model_number` VARCHAR(255) NOT NULL,
	`reg_number` VARCHAR(255) NOT NULL,
	`price_per_day` INT NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE `drivers`(
	`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`age` VARCHAR(255) NOT NULL,
	`cnic_no` VARCHAR(255) NOT NULl,
	`license_no` VARCHAR(255) NOT NULL,
	`price_per_day` INT NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `bookings`(
	`booking_id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`client_id` INT NOT NULL,
	`car_id` INT NOT NULL,
	`driver_id` INT DEFAULT NULL,
	`booking_date_start` DATE NOT NULL,
	`booking_date_end` DATE NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (car_id) REFERENCES cars(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (client_id) REFERENCES clients(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (driver_id) REFERENCES drivers(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `billings`(
	`id`INT NOT NULL PRIMARY KEY  AUTO_INCREMENT,
	`booking_id` INT NOT NULL,
	`total_cost` INT NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAUlt CURRENT_TIMESTAMP,
	FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON UPDATE CASCADE ON DELETE CASCADE
)